class Guess():

    def __init__(self):
        pass

    def start(self):
        print("""    Welcome to Mastermind, a game of logic and deduction! The goal of the game is to guess a secret code that has been generated by the computer.
    The code is a sequence of four colored pegs, chosen from a set of six possible colors. You will have ten chances to guess the code correctly.

    Each turn, you will make a guess by entering a sequence of four colors; ['W','Y','B','O','R','M']. The syntax is for example: "YYWW".
    The computer will then give you feedback on your guess by indicating how many of the pegs in your guess are the correct color and in the correct position,
    and how many are the correct color but in the wrong position. Using this feedback, you must deduce what the actual code is and make a new guess on the next turn.

    Remember, you only have ten chances to guess the code correctly, so use your deductive skills wisely! Good luck, and have fun playing Mastermind!\n""")

    def menu(self):
        guess = input("Guess: ")
        if len(guess) != 4:
            print("You mistyped, try again:")
            return False
        for i in guess:
            if i.islower():
                print("CAPS ON THIS TIME! No lowercase letters!")
                return False
            if i.isdigit():
                print("No digits fellow friend! Only letters!")
                return False        
        return guess